name: kreplemployee
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  get: ^4.6.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.9
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  credit_card_scanner: ^1.0.5
  showcaseview: ^2.0.3
  animations: ^2.0.11
  get_storage: ^2.1.1
  provider: ^6.1.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  data_table_2: ^2.5.9
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  http:
  marquee: ^2.2.3
  cached_network_image: ^3.3.1
  fl_chart: ^0.66.0
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.3.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  flutter_google_maps_webservices: ^1.1.1
  geocoding: ^2.2.2
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/annimations/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"



